const CONST = {
  BASE_URL: process.env.REACT_APP_BASE_URL,
  BASE_KEY: process.env.REACT_APP_BASE_KEY,
  BASE_FIREBASE_API_KEY: process.env.REACT_APP_FIREBASE_API_KEY,
  BASE_FIREBASE_AUTH_DOMAIN: process.env.REACT_APP_FIREBASE_AUTH_DOMAIN,
  BASE_FIREBASE_PROJECT_ID: process.env.REACT_APP_FIREBASE_PROJECT_ID,
  BASE_FIREBASE_STORAGE_BUCKET: process.env.REACT_APP_FIREBASE_STORAGE_BUCKET,
  BASE_FIREBASE_MESSAGING_SENDER_ID:
    process.env.REACT_APP_FIREBASE_MESSAGING_SENDER_ID,
  BASE_FIREBASE_APP_ID: process.env.REACT_APP_FIREBASE_APP_ID,
  BASE_FIREBASE_MEASUREMENT_ID: process.env.REACT_APP_FIREBASE_MEASUREMENT_ID,
};

export default CONST;
